baseurl = "http://masteringpostgresql.com/"
relativeURLs = false
languageCode = "en-us"
title = "Mastering PostgreSQL"

theme = "landing-page-hugo"
publishDir = "docs"

googleAnalytics = "UA-47059482-3"

[params]
        description = "Learn to use SQL to easily solve complex problems!"
        custom_css = ["css/local.css"]
        favicon = "/favicon.ico"
