baseurl = "http://masteringpostgresql.com/"
relativeURLs = false
languageCode = "en-us"
title = "Mastering PostgreSQL"

#theme = "landing-page-hugo"
theme = "universal"
publishDir = "docs"

googleAnalytics = "UA-47059482-3"

[params]
        description = "The Book that teaches developers to use SQL to easily solve complex problems!"
        custom_css = ["css/local.css"]
        favicon = "/favicon.ico"
        style = "blue"
        date_format = "January 2, 2006"
        copyright = "© 2017, Dimitri Fontaine"

[params.topbar]
        enable = false

[params.carousel]
        enable = true

[params.packages]
        enable = true
        title = "The Packages"
        subtitle = """
Mastering PostgreSQL in Application Developement comes in a choice of 4
packages. From the classic and to the point package ***The Book*** to the
***Enterprise Edtion***, your needs are covered. Our best sell is the ***Full
Edition***, be sure to check it out!
"""

[params.author]
        enable = true
        title = "About the Author"
        image = "/img/dim-rounded.png"
        subtitle = """

Hi! My name is **Dimitri Fontaine** and I have been using and contributing
to Open Source Software for the best of the last 20 years. I am a
**PostgreSQL Major Contributor** after having contributed *Extensions* and
*Event Triggers*, among other things.
<br>
<br>
I have been writing code almost daily for a very long time now, both in a
professional capacity and on my leisure time. I've also been a database
architect and a DBA on-call. As a developer I enjoy using SQL. As a database
architect, I like teaching advanced SQL techniques to my colleagues.
"""

[params.features]
    enable = true

[params.testimonials]
    enable = true
    title = "Interviews"
    subtitle = "<b><i>Mastering PostgreSQL in Application Development</i></b> includes interviews from developpers and SQL masters. PHP, Java, Python and Django get specific treatment in the book, which targets all application developers, whatever the language in use!"

[params.see_more]
    enable = true
    icon = "fa fa-book"
    title = "Get the Book!"

[params.facts]
    enable = true
    title = "What's in the Book?"

[params.recent_posts]
    enable = false

[menu]

# Main menu

[[menu.main]]
    name = "The Book"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Tapoueh.org"
    url  = "http://tapoueh.org/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 3

# [[menu.main]]
#     name = "Services"
#     url  = "/services/"
#     weight = 4
